server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://springsecurity.c3sv6gadpis1.ap-south-1.rds.amazonaws.com/eazybank
    username: admin
    password: mysqlspringsecurity
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security:
          web.FilterChainProxy: DEBUG